simulation:
  name: "Economic LLM Simulation"
  max_turns: 10
  termination:
    min_value: null
    max_value: null

llm:
  model: "gemma3:1b"
  host: "http://localhost:11434"
  timeout: 60.0
  max_retries: 1
  temperature: 0.7
  stream: true

agents:
  - name: "USA"
    type: econ_llm_agent
    initial_economic_strength: 100.0
  - name: "EU"
    type: econ_llm_agent
    initial_economic_strength: 95.0

validator:
  type: econ_llm_validator
  domain: economic
  permissive: true

engine:
  type: econ_llm_engine
  interest_rate: 0.025

logging:
  level: DEBUG
  format: json
